config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Add a root route if you don't have one...
  # We can use users#new for now, or replace this with the controller and action you want to be the site root:
  root 'pages#home'

  # sign up page with form:
  get 'register', to: 'users#new', as: :new_user

  # create (post) action for when sign up form is submitted:
  post 'users/', to: 'users#create'

  # show profile page for a user:
  get 'users/:id', to: 'users#show', as: :user

  # log in page with form:
  get '/login', to: 'sessions#new'

  # create (post) action for when log in form is submitted:
  post '/login', to: 'sessions#create'

  # delete action to log out:
  get '/logout', to: 'sessions#destroy'

  # pages:
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'

  # dark mode:
  get 'dark_mode', to: 'application#dark_mode'
  get 'light_mode', to: 'application#light_mode'

  # articles:
  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, :body, presence: true
  validates :title, length: { maximum: 140 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
  validates :email, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: 'must be a valid email address' }
  validates :password, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true, length: { minimun: 2, maximum: 50 }
  validates :email, presence: true, uniqueness: true, length: { minimun: 5, maximum: 255 }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: 'must be a valid email address' }
  validates :password, length: { minimum: 8 }
  validates :password_confirmation, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if User.exists?(session[:user_id])
      @current_user ||= User.find(session[:user_id])
    else
      session.delete(:user_id)
      nil
    end
  end

  def authorize
    redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
  end

  def dark_mode
    params[:dark_mode] = 'dark'
    cookies.permanent[:dark_mode] = params[:dark_mode]
    redirect_back(fallback_location: root_path)
  end

  def light_mode
    params[:dark_mode] = 'light'
    cookies.permanent[:dark_mode] = params[:dark_mode]
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authorize, except: %i[index show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to @article
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.user == current_user
      @article.destroy
      @article.comments.destroy_all
      redirect_to articles_path, status: :see_other
    else
      redirect_to @article, notice: "You can't delete this article"
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :subtitle, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to @article, notice: 'Comment was not created.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    if @comment.user == current_user || @article.user == current_user
      @comment.destroy
      redirect_to @article, status: :see_other, notice: 'Comment was successfully destroyed.'
    else
      redirect_to @article, notice: "You can't delete this comment"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # if logged in, redirect to user profile page:
    # redirect_to user_path(current_user) if logged_in?
  end

  def about; end
  def contact; end

  private

  def logged_in?
    # if there is a current user, return true:
    # !!current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      redirect_to user_path(current_user), notice: 'You are already logged in.'
    else
      render :new, locals: { login: {} }
    end
  end

  def create
    if current_user
      redirect_to user_path(current_user), notice: 'You are already logged in.'
    else
      user = User.find_by(email: params[:login][:email].downcase)

      if user&.authenticate(params[:login][:password])
        session[:user_id] = user.id
        flash[:success] = 'Logged in!'
        redirect_to user_path(user)
      else
        flash.now[:error] = 'Incorrect email or password, try again.'
        render :new, status: :unauthorized, locals: { login: params[:login] }
      end
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:alert] = 'Logged out!'
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    if current_user
      redirect_to user_path(current_user), notice: 'You are already logged in.'
    else
      render :new, locals: { user: {} }
    end
  end

  def create
    @user = User.new(user_params)
    @user.email.downcase!
    if @user.save
      flash[:success] = 'Account created successfully!'
      redirect_to login_path
    else
      flash.now[:error] = "Oops, couldn't create account. Please make sure you are using a valid email and password."
      render :new, status: :unprocessable_entity, locals: { user: @user }
    end
  end

  def show
    @user = User.find(params[:id])
    @funny_titles = ['Lord of the cats', 'Master of the universe', 'King of the world', 'God of the universe',
                     'Master of the cats', 'King of the universe', 'God of the world', 'Lord of the universe',
                     'Master of the world', 'God of the cats', 'King of the cats', 'Lord of the world',
                     'Master of the cats', 'King of the universe', 'God of the universe', 'Lord of the cats',
                     'Master of the world', 'God of the world', 'Lord of the universe']
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<section id="content">
  <section id="hero" class="chat"></section>
  <section id="container">
    <div class="hero-text">
      <div class="title">Edit Article</div>
    </div>
    <%= render "form", article: @article %>
    <%= link_to "Back", articles_path %>
  </section>
</section>

app/views/articles/index.html.erb
<section class="container mx-auto flex flex-wrap flex-col sm:flex-row items-center">
  <div class="flex flex-col w-full md:w-2/2 lg:w-1/3 justify-center xl:items-end overflow-y-hidden text-center xl:text-right">
    <div class="flex flex-col w-full justify-center items-center xl:items-end px-6 text-gray-800 dark:text-gray-200
			<p class="uppercase tracking-loose">Welcome our to</p>
			<h1 class="font-bold text-3xl my-4">Articles Dashboard</h1>
			<p class="leading-normal mb-4">Here you will find all our articles. You can read them and even create your own if you are a member!</p>
      <p class="leading-normal mb-4">Plus when you are a member you can comment on articles and even vote on them!</p>
			<a href="<%= new_article_path %>" class="bg-transparent hover:bg-gray-500 rounded shadow hover:shadow-lg py-2 px-4 border border-gray-900 dark:border-gray-100 hover:border-transparent transition">Create an article</a>
		</div>
  </div>
  <div class="flex flex-col w-full md:w-1/2 lg:w-1/3 justify-center lg:items-center overflow-y-hidden p-4 md:p-16 md:py-4 py-2 break-all">    
    <% if @articles.any? %>
      <% @articles.order('created_at DESC').limit(1).each do |article| %>
        <a href="<%= article_path(article) %>" class="transform -rotate-0 transition duration-700 ease-in-out hover:rotate-3">
          <figure class="flex flex-col items-center justify-center p-2 text-center backdrop-blur-sm border rounded-lg shadow-sm hover:shadow-lg transition">
            <h3 class="font-bold text-3xl pb-4 border-b border-gray-700 w-full text-center text-gray-700 dark:text-gray-200">Last Article</h3>
            <blockquote class="w-full mx-auto mb-2 text-gray-900 dark:text-gray-100">
              <h3 class="font-semibold text-lg my-4"><%= article.title %></h3>
              <p class="my-4 font-light text-sm"><%= article.body.truncate(280) %></p>
            </blockquote>
            <figcaption class="flex flex-col items-center justify-center space-x-3 text-gray-900 dark:text-gray-100">
              <div class="text-sm font-light"><%= article.created_at.strftime("%B %d, %Y") %> - <%= article.user.name %></div>
              <div class="text-sm font-light"><%= article.comments.count %> comments</div>
            </figcaption>
          </figure>
        </a>
      <% end %>
    <% else %>
          <figure class="flex flex-col items-center justify-center p-2 text-center backdrop-blur-sm border rounded-lg shadow-sm hover:shadow-lg transition">
            <h3 class="font-bold text-3xl pb-4 border-b border-gray-700 w-full text-center text-gray-700 dark:text-gray-200">Last Article</h3>
            <blockquote class="w-full mx-auto mb-2 text-gray-900 dark:text-gray-100">
            <h3 class="font-semibold text-2xl my-4">No articles yet</h3>
          <p class="my-4 font-light">Be the first to create an article!</p>
        </blockquote>
            <figcaption class="flex items-center justify-center space-x-3 text-gray-900 dark:text-gray-100">
            <a href="<%= new_article_path %>" class="bg-transparent hover:bg-gray-100 text-gray-100 hover:text-black rounded shadow hover:shadow-lg py-2 px-4 border border-gray-100 hover:border-transparent transition">Create an article</a>
            <a href="<%= new_user_path %>" class="bg-transparent hover:bg-gray-100 text-gray-100 hover:text-black rounded shadow hover:shadow-lg py-2 px-4 border border-gray-100 hover:border-transparent transition">Sign up</a>
          </figcaption>
      </figure>
    <% end %>
  </div>
  <div class="flex flex-col w-full md:w-1/2 lg:w-1/3 justify-center lg:items-center overflow-y-hidden p-4 md:p-16 md:py-4 py-2 break-all">    
    <% if @articles.any? %>
      <% # lets get the most commented article %>
      <% article = @articles.max_by { |article| article.comments.count } %>
      <a href="<%= article_path(article) %>" class="transform -rotate-0 transition duration-700 ease-in-out hover:rotate-3">
        <figure class="flex flex-col items-center justify-center p-2 text-center backdrop-blur-sm border rounded-lg shadow-sm hover:shadow-lg transition">
          <h3 class="font-bold text-3xl pb-4 border-b border-gray-700 w-full text-center text-gray-700 dark:text-gray-200">Most Commented</h3>
          <blockquote class="w-full mx-auto mb-2 text-gray-900 dark:text-gray-100">
            <h3 class="font-semibold text-lg my-4"><%= article.title %></h3>
            <p class="my-4 font-light text-sm"><%= article.body.truncate(280) %></p>
          </blockquote>
          <figcaption class="flex flex-col items-center justify-center space-x-3 text-gray-900 dark:text-gray-100">
            <div class="text-sm font-light"><%= article.created_at.strftime("%B %d, %Y") %> - <%= article.user.name %></div>
            <div class="text-sm font-light"><%= article.comments.count %> comments</div>
          </figcaption>
        </figure>
      </a>
    <% else %>
      <figure class="flex flex-col items-center justify-center p-2 text-center backdrop-blur-sm border rounded-lg shadow-sm hover:shadow-lg transition">
        <h3 class="font-bold text-3xl pb-4 border-b border-gray-700 w-full text-center text-gray-700 dark:text-gray-200">Most Commented</h3>
        <blockquote class="w-full mx-auto mb-2 text-gray-900 dark:text-gray-100">
          <h3 class="font-semibold text-2xl my-4">No articles yet</h3>
          <p class="my-4 font-light">Be the first to create an article!</p>
        </blockquote>
        <figcaption class="flex items-center justify-center space-x-3 text-gray-900 dark:text-gray-100">
          <a href="<%= new_article_path %>" class="bg-transparent hover:bg-gray-100 text-gray-100 hover:text-black rounded shadow hover:shadow-lg py-2 px-4 border border-gray-100 hover:border-transparent transition">Create an article</a>
          <a href="<%= new_user_path %>" class="bg-transparent hover:bg-gray-100 text-gray-100 hover:text-black rounded shadow hover:shadow-lg py-2 px-4 border border-gray-100 hover:border-transparent transition">Sign up</a>
        </figcaption>
      </figure>
    <% end %>
  </div>
</section>
<section class="container mx-auto flex flex-wrap flex-col md:flex-row items-center">
  <div class="flex flex-col w-full justify-center lg:items-start overflow-y-hidden"></div>
  <!-- Snippet -->
  <div class="w-full p-5 overflow-hidden">
    <!-- Table -->
    <div class="w-full mx-auto bg-white bg-opacity-90 shadow-lg rounded border border-gray-400">
      <header class="px-5 py-4 border-b border-gray-500">
        <h2 class="font-semibold text-gray-800">Articles</h2>
      </header>
      <div class="p-3">
        <table class="table-auto w-full">
          <thead class="text-xs font-semibold uppercase text-gray-100 bg-gray-500 border-b">
            <tr>
              <th class="p-2 hidden xl:table-cell">
                <div class="font-semibold">ID</div>
              </th>
              <th class="p-2 hidden md:table-cell">
                <div class="font-semibold">Author</div>
              </th>
              <th class="p-2">
                <div class="font-semibold">Title</div>
              </th>
              <th class="p-2 hidden md:table-cell">
                <div class="font-semibold">Date</div>
              </th>
              <th class="p-2 hidden xl:table-cell">
                <div class="font-semibold">Hour</div>
              </th>
              <th class="p-2 hidden xl:table-cell">
                <div class="font-semibold">Comments</div>
              </th>
            </tr>
          </thead>
          <tbody class="md:text-sm text-xs divide-y divide-gray-100">
            <% if @articles.any? %>
              <% @articles.order(created_at: :desc).each do |article| %>
                <tr>
                  <td class="py-2 hidden xl:table-cell text-center">
                    <a href="<%= user_path(article.user) %>" class="text-center p-3 text-gray-900 hover:text-gray-800 hover:underline">
                      <%= article.user.id %>
                    </a>
                  </td>
                  <td class="p-2 hidden md:table-cell">
                    <a href="<%= user_path(article.user) %>" class="p-3 text-gray-900 hover:text-gray-800 hover:underline">
                      <%= article.user.name %>
                    </a>
                  </td>
                  <td class="py-2">
                    <a href="<%= article_path(article) %>" class="p-3 text-gray-900 hover:text-gray-800 hover:underline">
                      <%= article.title.truncate(28) %>
                    </a>
                  </td>
                  <td class="p-2 hidden md:table-cell">
                    <div class="text-sm text-gray-700 text-center"><%= article.created_at.strftime("%B %d, %Y") %></div>
                  </td>
                  <td class="p-2 hidden xl:table-cell">
                    <div class="text-sm text-gray-700 text-center"><%= article.created_at.strftime("%H:%M") %></div>
                  </td>
                  <td class="p-2 hidden xl:table-cell">
                    <div class="text-sm text-center"><%= article.comments.count %></div>
                  </td>
                </tr>
              <% end %>
            <% else %>
              <tr>
                <td class="p-2">
                  <div class="text-left font-medium text-gray-800">No articles yet</div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/articles/new.html.erb
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<section class="px-4 flex sm:flex-row flex-col">
  <section class="sm:block hidden w-1/3 md:w-1/6 lg:w-1/12">
    <img src="<%= image_path('singing.svg') %>" alt="logo" class="w-full transform hover:scale-110 transition duration-500 ease-in-out">
  </section>
  <section class="w-full sm:w-2/3 md:w-5/6 lg:w-11/12">
    <div class="bg-white bg-opacity-70 shadow-lg rounded-lg border border-gray-200">
      <header class="px-5 py-4 border-b border-gray-100">
        <h2 class="font-semibold text-gray-800 text-xl flex justify-between">
          <div class="py-2"><%= @article.title %></div>
          <div>
            <% if current_user == @article.user %>
              <div class="flex flex-row justify-center gap-2">
                <div class="py-2">
                  <%= link_to "Modify", edit_article_path(@article),
                    class: "bg-green-900 hover:bg-green-800 text-white font-bold py-2 px-4 rounded-full w-full text-center text-sm" %>
                </div>
                <div class="py-2">
                  <%= link_to "Delete", article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                    class: "bg-red-900 hover:bg-red-800 text-white font-bold py-2 px-4 rounded-full w-full text-center text-sm" %>
                </div>
              </div>
            <% end %>
          </div>
        </h2>
      </header>
      <div class="p-3">
        <p class="text-gray-800 text-sm"><%= @article.body %></p>
      </div>
      <footer class="px-5 pb-1 border-t border-gray-100">
        <div class="flex flex-row justify-end gap-2">
          <div class="flex flex-row items-center text-gray-800 text-sm">
            <%= @article.created_at.strftime("%d/%m/%Y") %> - <%= @article.created_at.strftime("%H:%M") %>
            <p class="font-semibold pl-2">
              by: 
              <% if current_user %>
                <a href="<%= user_path(@article.user) %>" class="text-green-900 hover:text-green-800 hover:underline">
                  <%= @article.user.name %>
                </a>
              <% else %>
                <div class="text-green-900 pl-1">
                  <a href="<%= login_path %>" class="hover:text-green-800 hover:underline">
                    Log in to see the author
                  </a>
                </div>
              <% end %>
            </p>
          </div>
        </div>
      </footer>
    </div>
    <% if @article.comments.any? %>
      <div class="bg-white bg-opacity-70 shadow-lg border border-gray-200 mt-4">
        <header class="px-5 py-4 border-b border-gray-100">
          <h2 class="font-semibold text-gray-800 text-lg">Comments</h2>
        </header>
        <div class="p-3">
          <table class="table table-striped w-full">
            <thead>
              <tr>
                <th scope="col" class="text-right">Author</th>
                <th scope="col" class="text-left pl-2">Comment</th>
              </tr>
            </thead>
            <tbody>
              <%= render @article.comments %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
    <div class="bg-white bg-opacity-70 shadow-lg border border-gray-200 mt-4">
      <header class="px-5 py-4 border-b border-gray-100">
        <h2 class="font-semibold text-gray-800 text-lg">Add a comment</h2>
      </header>
      <div class="p-3">
        <% if current_user %>
          <%= render 'comments/form', article: @article %>
        <% else %>
          <div class="text-gray-800 text-sm">
            <p class="font-semibold">You need to be logged in to comment</p>
            <p class="font-semibold">If you don't have an account, you can create one <a href="<%= signup_path %>" class="text-green-900 hover:text-green-800 hover:underline">here</a></p>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</section>

app/views/comments/_comment.html.erb
<% unless !comment.persisted? %>
  <tr class="border-t border-gray-100 hover:bg-gray-400">
    <td class="text-gray-800 text-sm text-right font-semibold align-top flex flex-row justify-end"> 
      <% if current_user == comment.user || current_user == @article.user %>
        <div class="align-middle text-center pr-2">
          <%= link_to "X", article_comment_path(@article, comment), data: { turbo_method: :delete, turbo_confirm: "Are you sure
          you want to delete this comment?" }, class: "bg-red-900 hover:bg-red-800 text-white font-bold py-0.5 px-1 rounded-full w-full text-center text-xs" %>
        </div>
      <% end %>
      <%= comment.user.name %>:
    </td>
    <td>
      <div class="flex flex-row justify-between">
        <span class="text-gray-800 text-sm align-top pl-2 break-all w-11/12">
          <%= comment.body %>
        </span>
        <span class="text-gray-500 text-xs font-semibold text-right">
          <%= comment.created_at.strftime("%d/%m/%y") %> <%= comment.created_at.strftime("%H:%M") %>
        </span>
      </div>
    </td>
  </tr>
<% end %>

app/views/layouts/_footer.html.erb
<div class="p3 h-20 w-full"></div>
<footer class="fixed bottom-0 left-0 z-20 p-5 w-full shadow md:flex md:items-center md:justify-between text-center items-center
  text-gray-800 dark:text-gray-200 text-xs md:text-sm sm:text-center bg-gray-50 dark:bg-gray-900">
    <div class="mb-2 md:mb-0">© 2022 <a href="https://github.com/LuisHernandezCoding" class="hover:underline">LHC™ | Luis Hernandez Coding</a></div>
    <ul class="flex flex-wrap items-center justify-center">
      <li>
        <%= link_to "About", about_path, class: "m-3 md:m-6 hover:underline" %>
      </li>
      <li>
        <%= link_to "Contact", contact_path, class: "m-3 md:m-6 hover:underline" %>
      </li>
      <li>
        <% if cookies[:dark_mode] == "light" %>
          <%= link_to "Go Dark", dark_mode_path, class: "m-3 md:m-6 hover:underline" %>
        <% else %>
          <%= link_to "Go Light", light_mode_path, class: "m-3 md:m-6 hover:underline" %>
        <% end %>
      </li>
    </ul>
</footer>

app/views/layouts/_header.html.erb
<nav class="fixed w-full z-20 top-0 left-0 h-14 bg-purple-50 dark:bg-purple-900 shadow-lg">
  <div class="container flex flex-wrap items-center justify-between mx-auto h-full">
    <a href="<%= root_path %>" class="h-full flex items-center px-6">
        <%= image_tag "logo.svg", class: "h-6 mr-3 sm:h-9", alt: "logo" %>
        <h1 class="font-extrabold text-sm md:text-3xl">
          <span class="bg-clip-text text-transparent bg-blue-400">Members</span>
          <span class="bg-clip-text text-transparent bg-gradient-to-r from-blue-400 via-purple-500 to-pink-500">Only!!</span>
        </h1>
    </a>
    <div class="h-full items-center justify-between w-auto order-1 mr-2 md:mr-4" id="navbar-sticky">
      <ul class="h-full items-center flex flex-row mt-0 text-xs md:text-base border-0 font-bold">
        <% links_class = "h-full items-center px-2 md:px-4 flex bg-transparent text-purple-800 dark:text-purple-200 transition hover:bg-purple-600 hover:dark:bg-purple-400 hover:text-white dark:hover:text-purple-800" %>
        <li class="h-full items-center">
          <%= link_to 'Articles', articles_path, class: links_class %>
        </li>
        <li class="h-full items-center">
          <% if current_user %>
            <%= link_to 'Profile', user_path(current_user), class: links_class %>
          <% else %>
            <%= link_to 'Sign Up', new_user_path, class: links_class %>
          <% end %>
        </li>
        <li class="h-full items-center">
          <% if current_user %>
            <%= link_to 'Log out', logout_path, method: :delete, class: links_class %>
          <% else %>
            <%= link_to 'Log In', login_path, class: links_class %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="w-full h-24"></div>

app/views/pages/about.html.erb
<%= render "layouts/maintenance" %>

app/views/pages/contact.html.erb
<%= render "layouts/maintenance" %>

app/views/pages/home.html.erb
<section class="container mx-auto flex flex-wrap flex-col md:flex-row items-center">
  <!--Left Col-->
  <div class="flex flex-col w-full xl:w-2/5 justify-center lg:items-start overflow-y-hidden">
    <h1 class="my-4 text-3xl md:text-5xl text-black dark:text-white opacity-75 font-bold leading-tight text-center md:text-left">
      Welcome to
      <span class="bg-clip-text text-transparent bg-blue-600 dark:bg-blue-400">Members</span>
      <span class="bg-clip-text text-transparent bg-gradient-to-r
      from-blue-600 via-purple-500 to-pink-500
      dark:from-blue-400 dark:via-purple-500 dark:to-pink-500">Only!!</span>
      Give us a try!
    </h1>
    <p class="leading-normal text-base md:text-2xl mb-8 text-center md:text-left text-gray-800 dark:text-gray-200">
      Just a few clicks and you're in! Register now and get access to our exclusive members-only content.
    </p>
    <div class="w-full md:w-1/2 lg:w-2/3">
      <a href="<%= articles_path %>" class="inline-flex items-center w-full justify-center mx-auto p-3 font-extrabold rounded-md 
      hover:bg-opacity-50 dark:hover:bg-opacity-50  bg-purple-900 dark:bg-purple-200 transition duration-200 text-gray-100 dark:text-purple-900 hover:text-purple-200">
        <span class="ml-2 text-xl font-bold">Read our articles</span>
      </a>
    </div>
  </div>

  <!--Right Col-->
  <div class="w-full xl:w-3/5 p-10 overflow-hidden">
    <img class="mx-auto w-full transform -rotate-6 transition hover:scale-105 duration-700 ease-in-out hover:rotate-6" src="<%= image_path 'home.svg' %>">
  </div>
  <div class="w-full flex flex-row justify-center items-center space-x-4">
    <div class="w-full md:w-1/2">
      <a href="<%= login_path %>" class="inline-flex items-center w-full justify-center mx-auto p-3 font-extrabold rounded-md 
      bg-purple-900 dark:bg-purple-200 hover:bg-opacity-50 dark:hover:bg-opacity-50 transition duration-200 text-gray-100 dark:text-purple-900 hover:text-purple-200">
        <span class="ml-2 text-xl font-bold">Log in</span>
      </a>
    </div>
    <div class="w-full md:w-1/2">
      <a href="<%= new_user_path %>" class="inline-flex items-center w-full justify-center mx-auto p-3 font-extrabold rounded-md 
      bg-purple-900 dark:bg-purple-200 hover:bg-opacity-50 dark:hover:bg-opacity-50 transition duration-200 text-gray-100 dark:text-purple-900 hover:text-purple-200">
        <span class="ml-2 text-xl font-bold">Sign up</span>
      </a>
    </div>
  </div>
</section>